BROKERS: Source-UpdateSourceAsync
The-Standard-Organization/GitFyle.Core.Api pull request #78
Opened 2024-07-02 12:38 UTC by SlimAhmad

Closes #54

2024-07-02 16:53 UTC, cjdutoit commented on GitFyle.Core.Api/Brokers/Storages/StorageBroker.Sources.cs
> +           await UpdateAsync(student);
```suggestion
        public async ValueTask<Source> UpdateSourceAsync(Source source) =>
           await UpdateAsync(source);
```

2024-07-02 16:56 UTC, cjdutoit commented on GitFyle.Core.Api/Brokers/Storages/StorageBroker.cs
> +            await this.SaveChangesAsync();
Remember to detach the object as we don't want the context to keep track of changes to an entity after it has been saved.

```suggestion
            await this.SaveChangesAsync();
            DetachSavedEntity(@object);
```

2024-07-02 18:29 UTC, cjdutoit requested changes
Resolve conflicts

2024-07-02 21:28 UTC, cjdutoit commented on GitFyle.Core.Api/Brokers/Loggings/ILoggingBroker.cs
> +
remove empty line

2024-07-03 10:45 UTC, kandarpgautam commented
if this can be merged then I will have the UpdateAsync method.

2024-07-03 11:11 UTC, closed without merging