BROKERS: Repository - DeleteRepositoryAsync
The-Standard-Organization/GitFyle.Core.Api pull request #92
Opened 2024-07-03 11:49 UTC by Lezune

Closes #60

2024-07-03 15:41 UTC, cjdutoit requested changes
Resolve conflict

2024-07-08 05:19 UTC, Lezune commented
> Resolve conflict

@cjdutoit, Merge conflicts has been resolved. Main branch has been updated so additional conflicts might need to be resolved once the review of the changes have been approved.

2024-07-08 18:20 UTC, cjdutoit commented on GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Repository.cs
> +    internal partial interface IStorageBroker
This is the wrong file. I was expecting an addition on the existing `IStorageBroker.Repositories.cs`

2024-07-15 21:53 UTC, Lezune commented
Sorry! Still learning Github. Did not know that there was a re-review button in the top corner. Hopefully I did not slow things down.

2024-07-16 14:02 UTC, cjdutoit approved these changes

2024-07-16 14:16 UTC, cjdutoit commented on GitFyle.Core.Api/Brokers/Storages/StorageBroker.Repositories.cs
> +        public async ValueTask<Repository> DeleteRepositoryAsync(Repository repository) =>
Keep CRUD sequence.  Delete should go last

2024-07-16 14:34 UTC, cjdutoit approved these changes

2024-07-16 14:34 UTC, merged